数组的转置方法为 `.T` 只对矩阵有效，因此遇到向量要先将其转化为矩阵。

（1）向量的转置

In [2]:
import numpy as np

In [3]:
arr1 = np.arange(1,4)
print(arr1)
arr2 = arr1.reshape((1,-1))
print(arr2)
arr3 = arr2.T
print(arr3)

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


(2) 矩阵的转置

In [ ]:
arr1 = np.arange(4).reshape(2,2)
print(arr1)
arr2 = arr1.T
print(arr2)