In [2]:
import numpy as np
arr1 = np.arange(3)
arr2 = np.arange(4,7)
arr3 = np.concatenate([arr1, arr2])
print(arr3)

[0 1 2 4 5 6]


In [5]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.concatenate([a,b], axis=0)           #默认参数axis=0
print(c)
d = np.concatenate([a,b], axis=1)
print(d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
