In [7]:
import numpy as np
a = np.arange(10,90,10)
print(a)
arr1,arr2,arr3= np.split(a,[2,7])
print(arr1)
print(arr2)
print(arr3)

[10 20 30 40 50 60 70 80]
[10 20]
[30 40 50 60 70]
[80]


In [9]:
arr = np.arange(1,10).reshape(3,3)
print(arr)
arr1,arr2 = np.split(arr,[1])       #默认参数asis=0
print(arr1,'\n\n',arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]] 

 [[4 5 6]
 [7 8 9]]
