与 Python 列表一致，访问 NumPy 数组元素时使用中括号，索引由 0 开始。

In [4]:
import numpy as np

In [2]:
arr1 = np.arange(1,10)
print(arr1)
print(arr1[3])
print(arr1[-1])
arr1[3] = 100
print(arr1)

[1 2 3 4 5 6 7 8 9]
4
9
[  1   2   3 100   5   6   7   8   9]


In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2[0,2])
print(arr2[1,-2])
arr2[1,1] = 100
print(arr2)

[[1 2 3]
 [4 5 6]]
3
5
[[  1   2   3]
 [  4 100   6]]
