花式索引（Fancy indexing）又名“花哨的索引”，UP认为不应该用“花哨”来形容，这里的Fancy应取“华丽的、巧妙的、奢华的、时髦的”之义。
上一小节访问单个元素时，向量用arr1[x]，矩阵用arr2[x,y]。逗号在矩阵里用于区分行与列，这一小节，逗号新增一个功能，且不会与矩阵里的逗号混淆。

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(0,90,10)
print(arr1)
print(arr1[[0,2]])

[ 0 10 20 30 40 50 60 70 80]
[ 0 20]


In [3]:
arr2 = np.arange(1,17).reshape(4,4)
print(arr2)
print(arr2[[0,1],[0,1]])
print(arr2[[0,1,2],[2,1,0]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[1 6]
[3 6 9]


根据以上实例，花式索引也就是用向量来替代普通索引的行列元素，且花式索引输出的仍然是一个向量。

表 3-1 普通索引与花式索引的区别

| 索引方式 | 向量                | 矩阵                                   |
| -------- | ------------------- | -------------------------------------- |
| 普通索引 | arr1\[x₁]           | arr2\[x₁, y₁]                          |
| 花式索引 | arr1\[[x₁,x₂,…,xₙ]] | arr2\[[x₁,x₂,…,xₙ], [y₁,y₂,…,yₙ]] |