向量与列表切片的操作完全一致，因此本页内容在 Python 基础中均有涉及。


In [2]:
import numpy as np

In [ ]:
arr1 = np.arange(1,10)
print(arr1)
print(arr1[1:4])        #从索引[1]开始，切到索引[4]之前
print(arr1[1:])         #从索引[1]开始，切到结尾
print(arr1[:4])         #从数组开头开始，切到索引[4]之前

In [ ]:
#矩阵的切片
arr2 = np.arange(1,21).reshape(4,5)
print(arr2)
print(arr2[1:3,1:-1])
print(arr2[::3,::2])

In [ ]:
#提取矩阵的行
arr3 = np.arange(1,21).reshape(4,5)
print(arr3)
print(arr3[2,:])            #提取第二行
print(arr3[1:3,:])          #提取1至2行
print(arr3[2,:])            #规范的提取行
print(arr3[2])              #简便的提取行


In [ ]:
#提取矩阵的列
arr4 = np.arange(1,21).reshape(4,5)
print(arr4)
print(arr4[:,2])        #提取第2列（注意，提取的是向量）
print(arr4[:,1:3])      #提取1至2列

值得注意的是，提取某一个单独的列时，出来的结果是一个向量。其实这么做只是为了省空间，我们知道，列矩阵必须用两层中括号来存储，而形状为 1000 的向量，自然比形状为(1000,1)的列矩阵更省空间（节约了 1000 对括号）。

如果你真的想要提取一个列矩阵出来，示例如下。

In [34]:
arr5 = np.arange(1,16).reshape(3,5)
print(arr5)
cut = arr5[:,2]                 #提取第2列向量
print(cut)
cut = cut.reshape((-1,3))       #升级为矩阵，也可将后面写成-1  即将3写为-1  也可写为（-1,1）
print(cut)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 3  8 13]
[[ 3  8 13]]
