（1）数组切片仅是视图
与 Python 列表和 Matlab 不同，NumPy 数组的切片仅仅是原数组的一个视图。换言之，NumPy 切片并不会创建新的变量，示例如下。

In [1]:
import numpy as np

In [ ]:
arr = np.arange(10)
print(arr)
cut = arr[:3]       #创建arr的切片cut
print(cut)
cut[0] = 100        #对切片的数值进行改变
print(cut)
print(arr)          #原数组也被改变

习惯 Matlab 的用户可能无法理解，但其实这正是 NumPy 的精妙之处。试想一下，一个几百万条数据的数组，每次切片时都创建一个新变量，势必造成大量的内存浪费。因此，NumPy 的切片被设计为原数组的视图是极好的。

深度学习中为节省内存，将多次使用 arr[:]=<表达式> 来替代 arr=<表达式>。

（2）备份切片为新变量

如果真的需要为切片创建新变量（这种情况很稀少），使用 .copy() 方法。

In [2]:
arr = np.arange(10)
print(arr)
copy = arr[:3].copy()   #创建arr的拷贝切片
print(copy)
copy[0] = 100           #对拷贝切片的数值进行修改
print(copy)
print(arr)              #原数组不为所动

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[100   1   2]
[0 1 2 3 4 5 6 7 8 9]
