3.5 数组赋值仅是绑定
（1）数组赋值仅是绑定
与 NumPy 数组的切片一样，NumPy 数组完整的赋值给另一个数组，也只是绑定。换言之，NumPy 数组之间的赋值并不会创建新的变量，示例如下。

In [1]:
import numpy as np

In [4]:
arr1 = np.arange(1,10).reshape(3,3)
print(arr1)
arr2 = arr1             #把数值1赋给数值2
print(arr2)
arr2[0][0] = 100        #修改数组2
print(arr2)
print(arr1)             #原数组也被改变

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
