#数据类型

##整数型数组与浮点型数组

  为克服列表的缺点，一个Numpy数组只容纳一种数据类型，已节约内存，为方便起见，可将Numpy数组简单分为整数型数组与浮点型数组。

In [6]:
import numpy as np

In [10]:
#创建整数型数组
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [12]:
#创建浮点型数组
arr2 = np.array([1.0,2,3])
print(arr2)

[1. 2. 3.]


  注意，使用print输出Numpy数组后，元素之间没有逗号,这有两个好处，一是可以可将之与Python列表区分开来，二是避免逗号与小数点之间的混淆

##同化定理
往整数型数组里面插入浮点数，该浮点数自动截断为整数
浮点数组里面插入整数，该整数会自动升级为浮点数

In [8]:
arr1 = np.array([1,2,3])
arr1[0] = 100.9
print(arr1)

[100   2   3]


In [ ]:
arr2 = np.array([1.0,2,3])
arr2[1] = 10
print(arr2)

##共同改变定理
整数型数组与浮点型数组相互转换，规范的使用方法为。astype（）方法

In [ ]:
arr1 = np.array([1,2,3])
print(arr1)
arr2 = arr1.astype(float)       #转化为浮点数
print(arr2)
arr3 = arr2.astype(int)         #转化为整数
print(arr3)
#除了上述方法，也可通过整数型数组与浮点数做运算、整数型数组遇到除法、整数型数组与浮点型数组做运算进行相互转换

注意：整数型数组很好升级，单浮点型数组在运算过程中一般不会降级