（1）一维维度与二维数组考虑到深度学习中三维及其以上的数组出现次数少，我们后续主要讲解 NumPy 中的一维数组和二维数组，学了一维和二维后，很好类推到三维。
● 不同维度的数组之间，从外形上的本质区别是
一维数组使用 1 层中括号表示；
二维数组使用 2 层中括号表示；
三维数组使用 3 层中括号表示。
● 有些函数需要传入数组的形状参数，不同维度数组的形状参数为
一维数组的形状参数形如：x 或 (x,)；
二维数组的形状参数形如：(x,y)；
三维数组的形状参数形如：(x,y,z)。
● 现在以同一个序列进行举例当数组有 1 层中括号，如 [1 2 3]，则其为一维数组，其形状是 3 或 (3,)；
当数组有 2 层中括号，如 [[1 2 3]]，则其为二维数组，其形状是 (1,3)；
当数组有 3 层中括号，如 [[[1 2 3]]]，则其为三维数组，其形状是 (1,1,3)；
这里用后面要讲的 np.ones () 函数进行演示，只因其刚好需要传入形状参数。

In [2]:
import numpy as np

In [3]:
arr1 = np.ones(3)
print(arr1)

[1. 1. 1.]


In [4]:
arr2 = np.ones((1,3))
print(arr2)

[[1. 1. 1.]]


In [5]:
arr3 = np.ones((1,1,3))
print(arr3)

[[[1. 1. 1.]]]


可以通过shape方法查看形状

（2）不同维度数组之间的转换一维数组转二维数组，或是二维数组转一维数组，都要用到数组的重塑方法 .reshape()，该方法需要传入重塑后的形状（shape）参数。这个方法的巧妙之处在于，给定其他维度的数值后，剩下一个维度可以填 -1，让它自动计算。比如把一个 5 行 6 列的矩阵重塑为 3 行 10 列的矩阵时，若告知列的参数是 10，行的参数直接用 -1 替代即可，它会自动用 30（5×6 的结果）除以 10 来计算行数。首先，演示将一维数组升级为二维数组。


In [9]:
arr1 =np.arange(9)
print(arr1)
arr2 = arr1.reshape(3,3)        #一维升级为二维
print(arr2)
arr3 = arr2.reshape(-1)         #二维降为一维
print(arr3)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
